import "./globals.css"

export const metadata = {
    title: "Dashboard Server",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="icon"
                    type="image/svg+xml"
                    href="data:image/svg+xml,%3Csvg width='32' height='32' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23006dff' stroke-width='2'%3E%3Crect x='4' y='4' width='24' height='6' rx='2'/%3E%3Crect x='4' y='14' width='24' height='6' rx='2'/%3E%3Ccircle cx='8' cy='7' r='1.5' fill='%23006dff'/%3E%3Ccircle cx='8' cy='17' r='1.5' fill='%23006dff'/%3E%3C/g%3E%3C/svg%3E"
                />
            </head>
            <body className="font-optimistic-display antialiased">
                {children}
            </body>
        </html>
    )
}
